/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#137fec',
        'primary-dim': '#0048c1',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#c7d3ff',
        'primary-container': '#dbe1ff',
        'on-primary': '#f8f7ff',
        'on-primary-container': '#0048bf',
        'on-primary-fixed': '#003798',
        'on-primary-fixed-variant': '#0050d4',
        secondary: '#506076',
        'secondary-dim': '#44546a',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#c5d6f0',
        'secondary-container': '#d3e4fe',
        'on-secondary': '#f7f9ff',
        'on-secondary-container': '#435368',
        'on-secondary-fixed': '#314055',
        'on-secondary-fixed-variant': '#4d5d73',
        tertiary: '#615b77',
        'tertiary-dim': '#554f6b',
        'tertiary-fixed': '#e3dbfd',
        'tertiary-fixed-dim': '#d5cdee',
        'tertiary-container': '#e3dbfd',
        'on-tertiary': '#fcf7ff',
        'on-tertiary-container': '#524c68',
        'on-tertiary-fixed': '#3f3a54',
        'on-tertiary-fixed-variant': '#5c5672',
        error: '#9f403d',
        'error-dim': '#4e0309',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'on-error-container': '#752121',
        background: '#f7f9fb',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#cfdce3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f4f7',
        'surface-container': '#e8eff3',
        'surface-container-high': '#e1e9ee',
        'surface-container-highest': '#d9e4ea',
        'surface-variant': '#d9e4ea',
        'surface-tint': '#0053db',
        'on-surface': '#2a3439',
        'on-surface-variant': '#566166',
        'on-background': '#2a3439',
        outline: '#717c82',
        'outline-variant': '#a9b4b9',
        'inverse-primary': '#618bff',
        'inverse-surface': '#0b0f10',
        'inverse-on-surface': '#9a9d9f',
        'background-light': '#f6f7f8',
        'background-dark': '#101922',
      },
      fontFamily: {
        display: ['Inter', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['0.95rem', { lineHeight: '1.5rem' }],
        'label-md': ['0.875rem', { lineHeight: '1.25rem' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem' }],
        display: ['1.875rem', { lineHeight: '2.25rem' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
